version: 2
updates:


- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  reviewers:
  - credfeto
  assignees:
  - credfeto
  commit-message:
    prefix: "[Dependencies]"
  rebase-strategy: "auto"
  labels:
  - "submodule"
  - "dependencies"
  - "Changelog Not Required"


- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 99
  reviewers:
  - credfeto
  assignees:
  - credfeto
  allow:
  - dependency-type: all
  commit-message:
    prefix: "[Dependencies]"
  rebase-strategy: "auto"
  labels:
  - "github-actions"
  - "dependencies"
  - "Changelog Not Required"

