baseURL = "https://notes.markridgwell.com/"
title = "Mark Ridgwell | Notes"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy"]

[outputs]
home = ["HTML", "RSS","JSON"]


