baseURL = "https://notes.markridgwell.com/"
title = "Mark Ridgwell | Notes"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy"]

enableDarkMode = true
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

[outputs]
home = ["HTML", "RSS","JSON"]


