############################ Default configuration #########################
baseURL = "https://markridgwell.com/"
title = "Mark Ridgwell | Notes"
# theme
theme = "holy"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"


# disable language
disableLanguages = [""] # desable language from here


[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

